// coverage:ignore-file
// ignore_for_file: invalid_override, type_argument_not_callable, unnecessary_cast, avoid_redundant_argument_values
//
// TODO(maintainer): regenerate this file with
//   flutter pub run build_runner build --delete-conflicting-outputs
// once CI has a Dart 3.10-compatible mockito. The hand-edited
// `// ignore_for_file: invalid_override, type_argument_not_callable` directives
// above work around `cloud_firestore 6.x`'s new generic
// `WriteBatch.update<T>(DocumentReference<T>, T)` signature which the frozen
// Mockito 5.4.4 generator does not yet emit correctly.
//
// Mocks generated by Mockito 5.4.4 from annotations
// in paykari_bazar/test/services/ai_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:paykari_bazar/src/core/firebase/firestore_service.dart' as _i2;
import 'package:paykari_bazar/src/core/services/secrets_service.dart' as _i6;
import 'package:paykari_bazar/src/features/ai/domain/ai_work_type.dart' as _i8;
import 'package:paykari_bazar/src/features/ai/services/ai_provider.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> addDocument(
    String? collection,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDocument,
          [
            collection,
            data,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #addDocument,
            [
              collection,
              data,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateDocument(
    String? collection,
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [
            collection,
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateGeneric(
    String? collection,
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGeneric,
          [
            collection,
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> placeOrder(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeOrder,
          [data],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #placeOrder,
            [data],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> placeMedicineOrder(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeMedicineOrder,
          [data],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #placeMedicineOrder,
            [data],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            orderId,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> assignOrder(
    String? orderId,
    String? riderUid,
    String? riderName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignOrder,
          [
            orderId,
            riderUid,
            riderName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addProduct(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProduct(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleWishlist(
    String? uid,
    String? productId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleWishlist,
          [
            uid,
            productId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addCategory(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategory(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategoryOrder(
    String? id,
    int? order,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryOrder,
          [
            id,
            order,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addStore(Map<String, dynamic>? data) => (super.noSuchMethod(
        Invocation.method(
          #addStore,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateStore(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStore,
          [
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateStoreOrder(
    String? id,
    int? order,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoreOrder,
          [
            id,
            order,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStore(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteStore,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addLocation(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLocation,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLocation(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            id,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLocation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> performBatchUpdate(
    List<Map<String, dynamic>>? updates,
    String? collection,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performBatchUpdate,
          [
            updates,
            collection,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLoyaltySettings(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLoyaltySettings,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAppSettings(
    String? doc,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppSettings,
          [
            doc,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAppConfig(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppConfig,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSecrets(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSecrets,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLocalization(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocalization,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, dynamic>> watchLocalization() => (super.noSuchMethod(
        Invocation.method(
          #watchLocalization,
          [],
        ),
        returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
      ) as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Future<void> updateResellerAppStatus(
    String? id,
    String? status, {
    String? uid,
    String? shopName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateResellerAppStatus,
          [
            id,
            status,
          ],
          {
            #uid: uid,
            #shopName: shopName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> registerAsDonor(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerAsDonor,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markCommissionPaid(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markCommissionPaid,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> uploadImage(
    _i5.File? file,
    String? folder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [
            file,
            folder,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [SecretsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecretsService extends _i1.Mock implements _i6.SecretsService {
  MockSecretsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get deepSeekKeys => (super.noSuchMethod(
        Invocation.getter(#deepSeekKeys),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get genericKeys => (super.noSuchMethod(
        Invocation.getter(#genericKeys),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get cloudinaryCloudName => (super.noSuchMethod(
        Invocation.getter(#cloudinaryCloudName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#cloudinaryCloudName),
        ),
      ) as String);

  @override
  String get cloudinaryApiKey => (super.noSuchMethod(
        Invocation.getter(#cloudinaryApiKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#cloudinaryApiKey),
        ),
      ) as String);

  @override
  String getSecret(
    String? key, {
    String? fallback = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecret,
          [key],
          {#fallback: fallback},
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getSecret,
            [key],
            {#fallback: fallback},
          ),
        ),
      ) as String);

  @override
  List<String> getKeysByPrefix(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #getKeysByPrefix,
          [prefix],
        ),
        returnValue: <String>[],
      ) as List<String>);
}

/// A class which mocks [AIProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIProvider extends _i1.Mock implements _i7.AIProvider {
  MockAIProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i3.Future<bool> healthCheck() => (super.noSuchMethod(
        Invocation.method(
          #healthCheck,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> generate(
    String? prompt, {
    _i8.AiWorkType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generate,
          [prompt],
          {#type: type},
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [prompt],
            {#type: type},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<String> generateStream(
    String? prompt, {
    _i8.AiWorkType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStream,
          [prompt],
          {#type: type},
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
}
